### PR TITLE
fixed an exception which is thrown in case of facing null instead of an object in json

### PR DESCRIPTION
**Pull request by daxzel**
## Issue #20

```
{
  "object" : null 
}
```

Json parser ins't able to parse smth like that.

### CODE REVIEW

**Comment by daxzel** [comment]
Hey, could you commit this pull request as I'm really blocked by this bug and I need a release with this fix

**Comment by scr** [comment]
Can you please add a unit test for this case? Make sure the test fails before your fix and passes after, of course?

**Comment by daxzel** [comment]
Yeap. Will do

**Comment by scr** [comment]
FWIW, I tried to make a unit test, but couldn't reproduce - you'll have to include a .proto (add its processing in `pom.xml`) to show off the case that fails for you - it _could_ be a case where you've got a required message that is set to null, which actually should be an error (maybe?).  Perhaps the appropriate solution in that case, is to include a better error report.

I'm also curious whether, once you get a test that breaks without your change, the jackson version breaks as well…

**Comment by bivas** [comment]
@scr @daxzel Any updates on this issue?

**Comment by scr** [comment]
I don't see any updates including unit test that show the issue fixed.  Please reopen and add unit test if you still need this.

**Pull request closed without merging**
